Document: btrenamer
Title: Debian btrenamer Manual
Author: <insert document author here>
Abstract: This manual describes what btrenamer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/btrenamer/btrenamer.sgml.gz

Format: postscript
Files: /usr/share/doc/btrenamer/btrenamer.ps.gz

Format: text
Files: /usr/share/doc/btrenamer/btrenamer.text.gz

Format: HTML
Index: /usr/share/doc/btrenamer/html/index.html
Files: /usr/share/doc/btrenamer/html/*.html
